version: "2"
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - funlen
    - gocognit
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - testpackage
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        - FIXME
    importas:
      no-unaliased: true
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
