linters-settings:
  errcheck:
    check-type-assertions: true
    # https://github.com/golangci/golangci-lint/pull/4734.
    # Remove when upgrading to next golangci-lint release.
    ignore: ""
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  importas:
    no-unaliased: true
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - deadcode          # abandoned
    - depguard          # newer versions require explicit config to depend on anything outside of the Go stdlib
    - execinquery       # deprecated by author
    - exhaustivestruct  # replaced by exhaustruct
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - golint            # deprecated by Go team
    - gomnd             # replaced by mnd
    - ifshort           # deprecated by author
    - inamedparam       # convention is not followed
    - interfacer        # deprecated by author
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - maligned          # readability trumps efficient struct packing
    - mnd               # some unnamed constants are okay
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # named returns are fine; it's *bare* returns that are bad
    - nosnakecase       # deprecated in https://github.com/golangci/golangci-lint/pull/3065
    - scopelint         # deprecated by author
    - structcheck       # abandoned
    - testpackage       # internal tests are fine
    - varcheck          # abandoned
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude-dirs-use-default: false
  exclude-rules:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - linters:
      - err113
      - goerr113
      text: "do not define dynamic errors"
