run:
  skip-dirs-use-default: false
linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - errcheck
    - execinquery
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - logrlint
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  disable-all: true
