version: "2"
linters:
  default: all
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # newer versions require explicit config to depend on anything outside of the Go stdlib
    - funlen            # rely on code review to limit function length
    - godoclint         # we run this separately since we use a fork
    - gocognit          # dubious "cognitive overhead" quantification
    - inamedparam       # convention is not followed
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # some unnamed constants are okay
    - nlreturn          # generous whitespace violates house style
    - nonamedreturns    # named returns are fine; it's *bare* returns that are bad
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
        # temporary hacks, and use godox to prevent committing them.
        - FIXME
    importas:
      no-unaliased: true
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
        # Don't ban use of fmt.Errorf to create new errors, but the remaining
        # checks from err113 are useful.
          - err113
        text: do not define dynamic errors
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
