name: Update bufbuild/buf Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release (e.g. x.y.z)
        required: true
permissions:
  contents: write
  pull-requests: write
env:
  RELEASE_BUF_VERSION: ${{ github.event.inputs.version }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input version
        if: ${{ startsWith(github.event.inputs.version, 'v') }}
        run: |
          echo "error: version must not start with 'v'."
          exit 1
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Update Buf Version
        run: make updatebufversion
      - name: Create PR
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284
        with:
          add-paths: .
          commit-message: "Update bufbuild/buf version to ${{ env.RELEASE_BUF_VERSION }}"
          branch: buf-${{ env.RELEASE_BUF_VERSION }}
          delete-branch: true
          title: "Update bufbuild/buf version to ${{ env.RELEASE_BUF_VERSION }}"
          body: "Update bufbuild/buf version to newly released version, v${{ env.RELEASE_BUF_VERSION }}."
