name: Update bufbuild/buf Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release (e.g. x.y.z)
        required: true
env:
  RELEASE_BUF_VERSION: ${{ github.event.inputs.version }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input version
        if: ${{ startsWith(github.event.inputs.version, 'v') }}
        run: |
          echo "error: version must not start with 'v'."
          exit 1
      - name: Get GitHub app token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: #TODO: get new token
          private-key: #TODO: get new token
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
      - name: Update Buf Version
        run: make updatebufversion
      - name: Create PR
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          BRANCH="release/v${VERSION}"
          git switch -C ${BRANCH}
          git add PKGBUILD .SRCINFO
          git commit -m "Update version to ${VERSION}"
          git push --set-upstream origin --force ${BRANCH} 
          gh pr create --title "Release v${VERSION}" --body "Release prepared for ${VERSION}"
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
